Repository espressif/developer-portal, pull requests merged in 2025-02, with the labels that each got.

#394 blog:Add blog post on github copilot in espressif-ide
  content/blog/2025/02/github-copilot-in-espressif-ide/assets/copilot-chat.webp
  content/blog/2025/02/github-copilot-in-espressif-ide/assets/copilot-marketplace.webp
  content/blog/2025/02/github-copilot-in-espressif-ide/assets/copilot-menu.webp
  content/blog/2025/02/github-copilot-in-espressif-ide/assets/copilot-with-espressif-ide.webp
  content/blog/2025/02/github-copilot-in-espressif-ide/assets/preferences.webp
  content/blog/2025/02/github-copilot-in-espressif-ide/featured-copilot.webp
  content/blog/2025/02/github-copilot-in-espressif-ide/index.md
Labels: Status: Pending Merge

#396 blog: announce ESP-TEE framework
  assets/img/authors/mahavir-jain.webp
  content/blog/2025/02/announcing-esp-tee/featured-tee.webp
  content/blog/2025/02/announcing-esp-tee/img/esp-tee.webp
  content/blog/2025/02/announcing-esp-tee/index.md
  data/authors/mahavir-jain.json
Labels: Status: Awaiting Response, GitLab-Sync-Merge

#401 blog: add the rainmaker over thread solution post
  content/blog/2025/02/rainmaker-over-thread/featured-rainmaker-thread.webp
  content/blog/2025/02/rainmaker-over-thread/img/rainmaker-thread-app.webp
  content/blog/2025/02/rainmaker-over-thread/img/rainmaker-topology.webp
  content/blog/2025/02/rainmaker-over-thread/index.md
Labels: GitLab-Sync-Merge
