Repository espressif/developer-portal, pull requests merged in 2025-09, with the labels that each got.

#546 Add blog-post on esp-wifi-remote
  content/blog/2025/09/esp-wifi-remote/featured.webp
  content/blog/2025/09/esp-wifi-remote/img/at.drawio
  content/blog/2025/09/esp-wifi-remote/img/at.webp
  content/blog/2025/09/esp-wifi-remote/img/eppp.drawio
  content/blog/2025/09/esp-wifi-remote/img/eppp.webp
  content/blog/2025/09/esp-wifi-remote/img/hosted.drawio
  content/blog/2025/09/esp-wifi-remote/img/hosted.webp
  content/blog/2025/09/esp-wifi-remote/img/wifi_experience_1.drawio
  content/blog/2025/09/esp-wifi-remote/img/wifi_experience_1.webp
  content/blog/2025/09/esp-wifi-remote/img/wifi_experience_2A.drawio
  content/blog/2025/09/esp-wifi-remote/img/wifi_experience_2A.webp
  content/blog/2025/09/esp-wifi-remote/img/wifi_experience_2B.drawio
  content/blog/2025/09/esp-wifi-remote/img/wifi_experience_2B.webp
  content/blog/2025/09/esp-wifi-remote/index.md
Labels: needs review

#556 Landing page update with September featured articles
  content/_index.md
Labels: needs review, Priority: High

#555 fix: update relative links in assignments and lectures for consistency
  content/workshops/esp-idf-basic/assignment-1-1/index.md
  content/workshops/esp-idf-basic/assignment-1-2/index.md
  content/workshops/esp-idf-basic/assignment-2-1/index.md
  content/workshops/esp-idf-basic/assignment-2-2/index.md
  content/workshops/esp-idf-basic/assignment-2-3/index.md
  content/workshops/esp-idf-basic/assignment-3-1/index.md
  content/workshops/esp-idf-basic/assignment-3-2/index.md
  content/workshops/esp-idf-basic/assignment-3-3/index.md
  content/workshops/esp-idf-basic/lecture-1/index.md
  content/workshops/esp-idf-basic/lecture-2/index.md
  content/workshops/esp-idf-basic/lecture-3/index.md
Labels: needs review

#564 feat: add article about SPI Flash usage with NuttX
  content/blog/2025/09/nuttx-storing-data-spi-flash/featured.webp
  content/blog/2025/09/nuttx-storing-data-spi-flash/imgs/menuconfig_spi_flash_config.webp
  content/blog/2025/09/nuttx-storing-data-spi-flash/index.md
Labels: GitLab-Sync-Merge
